services:
  - type: web
    name: kyzylordahub-telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: INSTAGRAM_URL
        sync: false
      - key: COURSE_PLATFORM_URL
        sync: false
      - key: RENDER_EXTERNAL_URL
        value: https://kyzylordahub-telegram-bot-1.onrender.com
